version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "10080:8888"
    volumes:
      - ./datasets:/home/jovyan/work/datasets
      - ./notebooks:/home/jovyan/work/notebooks
      - ./libs:/home/jovyan/work/libs
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start.sh jupyter lab --LabApp.token='${JUPYTER_TOKEN}' --LabApp.password='' --LabApp.ip='0.0.0.0' --LabApp.allow_origin='*'
    restart: unless-stopped